version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: project_container
    environment:
      MYSQL_DATABASE: vaishsakila 
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    networks:
      - ola_network


  springboot:
    build: .
    container_name: sakila_app
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    networks:
      - ola_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://vaish-db-sakila.cxbxe7ypeoyt.us-east-1.rds.amazonaws.com:3306/vaishsakila
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 12345678

networks:
  ola_network:
    driver: bridge
